version: "3.3"
services:
  duan-nginx:
    image: leonxi/duan-nginx
    hostname: duan-nginx

    ports:
      - target: 80
        published: 8088
        protocol: tcp
        mode: host
    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  duan-zuul:
    image: leonxi/duan-zuul
    hostname: duan-zuul
    depends_on:
      - duan-mysql

    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  duan-aba:
    image: leonxi/duan-auth
    hostname: duan-aba
    depends_on:
      - duan-mysql

    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  duan-auo:
    image: leonxi/duan-auth-origin
    hostname: duan-auo
    depends_on:
      - duan-mongo

    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  duan-abd:
    image: leonxi/duan-grant
    hostname: duan-abd
    depends_on:
      - duan-mysql

    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

  duan-aac:
    image: leonxi/duan-home
    hostname: duan-aac
    depends_on:
      - duan-mysql

    networks:
      - duan-network-overlay
    deploy:
      replicas: 1
      endpoint_mode: dnsrr

volumes:
  mysql-data:
  mongo-data:

networks:
  duan-storage_duan-network-overlay:
    external: true

